"""four tables — leetcode_problems, leetcode_log, pending_review, tutor_lessons

Implements the schema in docs/business-requirements.md §5. The four tables are
created here so the container entrypoint's `alembic upgrade head` provisions
them on first deploy. See docs/architecture.md §7 for the schema choices
(slug PK, no DB-level "at most 2 open per day" constraint, DATE not TIMESTAMPTZ).

Revision ID: 0002
Revises: 0001
Create Date: 2026-07-27
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leetcode_problems',
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('difficulty', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('tags', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('solved', sa.Boolean(), nullable=False),
    sa.Column('last_attempted', sa.Date(), nullable=True),
    sa.Column('times_attempted', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('slug')
    )
    op.create_table('tutor_lessons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.Column('times_reinforced', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tutor_lessons_active'), 'tutor_lessons', ['active'], unique=False)
    op.create_table('leetcode_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('problem_slug', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('time_spent_min', sa.Integer(), nullable=True),
    sa.Column('tutor_feedback', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('lesson_title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['problem_slug'], ['leetcode_problems.slug'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pending_review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('google_task_id', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('problem_slug', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('problem_title', sqlmodel.sql.sqltypes.AutoString(length=300), nullable=False),
    sa.Column('proposed_at', sa.Date(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.ForeignKeyConstraint(['problem_slug'], ['leetcode_problems.slug'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_review_message_id'), 'pending_review', ['message_id'], unique=False)
    op.create_index(op.f('ix_pending_review_proposed_at'), 'pending_review', ['proposed_at'], unique=False)
    op.create_index(op.f('ix_pending_review_status'), 'pending_review', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pending_review_status'), table_name='pending_review')
    op.drop_index(op.f('ix_pending_review_proposed_at'), table_name='pending_review')
    op.drop_index(op.f('ix_pending_review_message_id'), table_name='pending_review')
    op.drop_table('pending_review')
    op.drop_table('leetcode_log')
    op.drop_index(op.f('ix_tutor_lessons_active'), table_name='tutor_lessons')
    op.drop_table('tutor_lessons')
    op.drop_table('leetcode_problems')
    # ### end Alembic commands ###
